### ISSUE TITLE
Clock in the demo 

### ISSUE THREAD

**Issue by KrishnaPG** [robfallows/tunguska-gauge#3]
Good work. Thanks for sharing it.

The clock in the demo is having problem with 12 not rendering at the correct position - The marker is slightly off to right. Would be great if it could be fixed.

![image](https://cloud.githubusercontent.com/assets/4610831/10153727/ee4bfd9e-667c-11e5-8315-9446e6a8cb7d.png)

**Comment by robfallows** [comment]
That's weird. The grabbed screen shot in the README is correct, so I wonder when that started happening. Leave it with me.

**Comment by robfallows** [comment]
Fixed and republished the theme pack (typo in the clock definition JSON). Thanks for the heads up :smile:
